mutiple students check added

diff --git a/exercise/Makefile b/exercise/Makefile
--- a/exercise/Makefile
+++ b/exercise/Makefile
@@ -1,11 +1,8 @@
-NAME_STUDENT=student
-NAME_CORRECT=correct
 FLAGS=-Wall -Wextra
 OBJ_STUDENT_DIR=obj_student/
-OBJ_CORRECT_DIR=obj_correct/
 RANDOM_UTILS=../random_testing_units/random_testing_units.c
-COR_DIR=correct_task/
-STU_DIR=student_task/
+STU_DIR=$(DIR)
+NAME_STUDENT=task_$(STU_DIR)
 
 OK='\033[0;32m'
 FAIL='\033[0;31m'
@@ -20,29 +17,22 @@ else
 	EXT=.cpp
 endif
 
-FILES_CORRECT=$(addprefix $(COR_DIR), $(CFILES)) 
 FILES_STUDENT=$(addprefix $(STU_DIR), $(CFILES))
 
-OBJ_CORRECT=$(addprefix $(OBJ_CORRECT_DIR), $(CFILES:$(EXT)=.o))
 OBJ_STUDENT=$(addprefix $(OBJ_STUDENT_DIR), $(CFILES:$(EXT)=.o))
 
-all: random copy_main $(NAME_STUDENT) $(NAME_CORRECT) 
-	mkdir -p outputs diffs leakchecks
-	echo $(LEAK)
+all: random copy_main $(NAME_STUDENT) 
+	mkdir -p logs
+	mkdir -p logs/outputs logs/diffs logs/leakchecks logs/results
 ifeq ($(COMMAND_ARGS), 0)
-	./student > outputs/student_answer
-	./correct > outputs/correct_answer
-	@diff student_answer correct_answer > diffs/difference && echo "TEST $(OK)OK :)$(NC)" && rm -rf diffs/difference \ 
-	|| echo "$(FAIL)TEST FAILED :($(NC)"
+	./task > logs/outputs/$(NAME_STUDENT)
+	@diff logs/outputs/$(NAME_STUDENT) correct_outputs/output > logs/diffs/difference_$(NAME_STUDENT) &&
+	echo "TEST $(OK)OK :)$(NC)" && rm -rf logs/diffs/difference_$(NAME_STUDENT) && echo "OK" > logs/results/result_$(NAME_STUDENT) \ 
+	|| echo "$(FAIL)TEST FAILED :($(NC)" && echo "TEST FAILED" > logs/results/result_$(NAME_STUDENT)
 else
 	python3 arg_test.py $(LEAK) 
 endif
 	@rm -rf student.dSYM
-$(OBJ_CORRECT): $(OBJ_CORRECT_DIR)%.o: $(COR_DIR)%$(EXT)
-	$(CC) -std=$(STDRD) -c $(FLAGS) $< -o $@
-
-$(NAME_CORRECT): $(OBJ_CORRECT) $(NAME_STUDENT)
-	$(CC) $(FLAGS) $(OBJ_CORRECT) obj_utils/random_testing_units.o -o $(NAME_CORRECT)
 
 $(OBJ_STUDENT): $(OBJ_STUDENT_DIR)%.o: $(STU_DIR)%$(EXT)
 	$(CC) -std=$(STDRD) -c $(FLAGS) $< -o $@
@@ -51,20 +41,20 @@ $(NAME_STUDENT): $(OBJ_STUDENT)
 	$(CC) -std=$(SRDRD) $(FLAGS) $(OBJ_STUDENT) obj_utils/random_testing_units.o -o $(NAME_STUDENT)
 
 clean:
-	/bin/rm -rf $(OBJ_STUDENT_DIR) $(OBJ_CORRECT_DIR) obj_utils
+	/bin/rm -rf $(OBJ_STUDENT_DIR)  obj_utils
 
 fclean: clean
-	/bin/rm -rf $(NAME_CORRECT) $(NAME_STUDENT)
+	/bin/rm -rf $(NAME_STUDENT)
 
-re: fclean all
+re: fclean finish all
 
 random: ../random_testing_units/random_testing_units.h
-	mkdir -p $(OBJ_CORRECT_DIR) $(OBJ_STUDENT_DIR) obj_utils
+	mkdir -p $(OBJ_STUDENT_DIR) obj_utils
 	$(CC) -std=$(STDRD) -c $(FLAGS) $(RANDOM_UTILS) -o obj_utils/random_testing_units.o
 
 copy_main:
 ifeq ($(COMMAND_ARGS), 0)
-	cp correct_task/main$(EXT) student_task
+	cp main$(EXT) $(STU_DIR)
 endif
 
 leakcheck:
